In [1]:
result =0
for i in range(100):
    result +=i

In [2]:
result

4950

In [4]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
import numpy as np
np.array([1,2,3,4,5])
#Numpy array: 배열의 모든 요소가 같은 타입이어야 함, 타입이 일치하지 ㅇ낳으면 가능한 경우 상위 타입을 취함


array([1, 2, 3, 4, 5])

In [7]:
np.array([3.14,4,2,3])
# 정수 -> 부등 소수점으로 반환


array([3.14, 4.  , 2.  , 3.  ])

In [9]:
#array,의 dtype 지정
np.array([1,2,3,4], dtype= 'float')

array([1., 2., 3., 4.])

In [10]:
np.array([range(i,i+3)for i in[2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [11]:
#0으로 가득찬 길이 10의 정수 배열
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
#1로 채운 3*5 실수형 배열 만들기
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
#3.14로 채운 3*5 배열 만들기
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [14]:
#선형 수열로 채운 배열 만들기
#0에서 시작해서 2씩 더해서 20까지 채운
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
#0,1 사이에 일정한 간격을 가진 다섯개의 값으로 채운 배열 만들기
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
#균등하게 분포된 3*3 배열 만들기
#0과 1사이의 난수로 챙ㅁ
np.random.random((3,3))

array([[0.15462285, 0.58358321, 0.72147814],
       [0.1976192 , 0.24154428, 0.7279965 ],
       [0.13556554, 0.79138816, 0.00717906]])

In [18]:
#정규분포의 난수로 채운 3*3 배열
np.random.normal(0,1,(3,3))

array([[ 0.55185641,  0.83929477,  2.05063155],
       [-1.10535087,  0.16863902,  1.66127903],
       [-0.58920544, -0.0643989 ,  0.38183283]])

In [19]:
#[0,10] 구간의 임의의 정수로 채운 3*3 배열 만들기
np.random.randint(0,10,(3,3))

array([[5, 4, 0],
       [4, 5, 1],
       [1, 0, 9]], dtype=int32)

In [20]:
#3*3 배열의 단위행렬 만들기
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.random.seed(0)

#1차원 배열
x1=np.random.randint(10,size=6)
#2차원 배열
x2=np.random.randint(10,size=(3,4))
#3차원 배열
np.random.randint(10,size=(3,4,5))

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]], dtype=int32)

In [22]:
x1

array([5, 0, 3, 3, 7, 9], dtype=int32)

In [27]:
x1[5]

np.int32(9)

In [28]:
x1[-1]

np.int32(9)

In [29]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [30]:
x2[0,0]

np.int32(3)

In [31]:
x2[0]

array([3, 5, 2, 4], dtype=int32)

In [32]:
x2[0,0] = 12

In [34]:
#numpy 배열은 고정타입을 가지므로 정수배열에 실수를 삽입해도 소숫점 아래로 잘ㄻ
x1[0]=3.14
x1

array([3, 0, 3, 3, 7, 9], dtype=int32)

In [35]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#첫 5개 요소
x[:5]

array([0, 1, 2, 3, 4])

In [38]:
#인덱스 5다음 요소
x[5:]

array([5, 6, 7, 8, 9])

In [39]:
#중간 배열 추출
x[3:5]

array([3, 4])

In [40]:
#하나 걸러 하나씩의요소로 구성된 배열
x[::2]

array([0, 2, 4, 6, 8])

In [41]:
#인덱스 1에서 시작해 하나 걸러 하나씩 요소로 구성된 배열
x[1::2]

array([1, 3, 5, 7, 9])

In [42]:
#a모든 요소를 거꾸로 나열
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [44]:
#기존 인덱스 3부터 하나 걸러 하나씩 요소를 거꾸로 나열
x[3::-1]

array([3, 2, 1, 0])

In [45]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [47]:
#2개의 행, 2개의 열
x2[:2,:2]

array([[12,  5],
       [ 7,  6]], dtype=int32)

In [54]:
#모든 행, 한 열 걸러 하나씩
x2[:3,::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]], dtype=int32)

In [57]:
#역으로 반환
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]], dtype=int32)

In [58]:
#x2 첫번째 열
print(x2[:,0])

[12  7  1]


In [59]:
#x2 첫번째 행
print(x2[0,:])

[12  5  2  4]


In [63]:
#사본과 뷰
#배열 슬라이스가 배열 데이터의 사본이 아니라 뷰를 반환
#즉 배열의 일부를 추출하고 하위 배열을 수정하면 원본도 수정된다
x2_sub = x2[:2,:2]
x2_sub

array([[12,  5],
       [ 7,  6]], dtype=int32)

In [68]:
x2_sub[0,0]=99
x2_sub[0,0]

np.int32(99)

In [66]:
x2

array([[9, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [67]:
#사본 만들기
x2_sub_copy=x2[:2,:2].copy()
#사본에서는 하위 배열을 수정해도 원본은 바꾸지 않음

In [70]:
#배열 재구조화
#행 데이터를 2차원(3*3으로 변환
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
x=np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [72]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [73]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [74]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [75]:
#배열연결
x =np.array([1,2,3])
y =np.array([3,4,5])
np.concatenate([x,y])

array([1, 2, 3, 3, 4, 5])

In [78]:
grid =np.array([[1,2,3],
               [4,5,6]])
#첫번째 축(열) 따라 연결
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [79]:
#두번째 축(행)을 따라 연결
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [81]:
#배열분할
x=[1,2,3,4,5,6,7,8,9]
#np.split(x,[분할지점])
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [4 5] [6 7 8 9]


In [83]:
# 배열 산술 연산
# 덧셈, 뺄셈, 곱셈, 나눗셈 모두 사용가능
x=np.arange(4)
print("x    =",x)
print("x + 5=",x+5)
print("x - 5=",x-5)
print("x * 2=",x*2)
print("x / 2=",x/2)
#바닥 나눗셈
print("x // 2=",x//2)
#제곱
print("x ** 2=",x**2)
#나머지 연산
print("x %2=",x%2)
#원하는 만큼 함께 사용가능하고, 표준 연산순서를 따름

x    = [0 1 2 3]
x + 5= [5 6 7 8]
x - 5= [-5 -4 -3 -2]
x * 2= [0 2 4 6]
x / 2= [0.  0.5 1.  1.5]
x // 2= [0 0 1 1]
x ** 2= [0 1 4 9]
x %2= [0 1 0 1]


In [85]:
#절댓값
x=[-1,0,1]
np.absolute(x)
np.abs(x)






array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [ ]:
# 지수와 로그
# e의 x제곱
np.exp(x) 
# 2의 x제곱  
np.exp2(x)
# 3의 x제곱     
np.power(3, x)  
#로그
np.log(x)   
np.expm1(x)
np.log1p(x)

In [86]:
# 삼각함수
theta = np.linspace(0, np.pi, 3)  
#사인값   
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [87]:
#집계함수

L=np.random.random(100)
L

array([0.65279032, 0.63505887, 0.99529957, 0.58185033, 0.41436859,
       0.4746975 , 0.6235101 , 0.33800761, 0.67475232, 0.31720174,
       0.77834548, 0.94957105, 0.66252687, 0.01357164, 0.6228461 ,
       0.67365963, 0.971945  , 0.87819347, 0.50962438, 0.05571469,
       0.45115921, 0.01998767, 0.44171092, 0.97958673, 0.35944446,
       0.48089353, 0.68866118, 0.88047589, 0.91823547, 0.21682214,
       0.56518887, 0.86510256, 0.50896896, 0.91672295, 0.92115761,
       0.08311249, 0.27771856, 0.0093567 , 0.84234208, 0.64717414,
       0.84138612, 0.26473016, 0.39782075, 0.55282148, 0.16494046,
       0.36980809, 0.14644176, 0.56961841, 0.70373728, 0.28847644,
       0.43328806, 0.75610669, 0.39609828, 0.89603839, 0.63892108,
       0.89155444, 0.68005557, 0.44919774, 0.97857093, 0.11620191,
       0.7670237 , 0.41182014, 0.67543908, 0.24979628, 0.31321833,
       0.96541622, 0.58846509, 0.65966841, 0.53320625, 0.23053302,
       0.39486929, 0.61880856, 0.47486752, 0.47013219, 0.71607

In [88]:
#합계
print(np.sum(L))

52.12818058833702


In [89]:
#최솟값, 최댓값
min(L), max(L)

(np.float64(0.009356704856532616), np.float64(0.9952995676778876))

In [91]:
#배열 연산: 브로드 캐스팅
#배열의 요소 단위로 수행

a=np.array([0,1,2])
b=np.array([5,5,5])
a+b

array([5, 6, 7])

In [92]:
#값 5를 배열 [5,5,5]로 확장하거나 복제하고 그 결과를 더하는 연산으로 생각
a+5

array([5, 6, 7])

In [93]:
#다른 크기의 배열끼리의 연산
M =np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [94]:
#a는 M에 맞추기 위해 두번째 차원까지 확장/브로드캐스팅
M+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [95]:
a=np.arange(3)
b=np.arange(3)[:,np.newaxis]
a,b

(array([0, 1, 2]),
 array([[0],
        [1],
        [2]]))

In [96]:
#a와 b는 서로 향상을 맞추기 위해 브로드캐스팅 한다
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])